/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsIndexRouteImport } from './routes/units.index'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as MaintenanceIndexRouteImport } from './routes/maintenance.index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as AccountingIndexRouteImport } from './routes/accounting.index'
import { Route as UnitsIdRouteImport } from './routes/units.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIndexRoute = UnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceIndexRoute = MaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingIndexRoute = AccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsIdRoute = UnitsIdRouteImport.update({
  id: '/units/$id',
  path: '/units/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/accounting/': typeof AccountingIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/accounting': typeof AccountingIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/maintenance': typeof MaintenanceIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/units': typeof UnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/units/$id': typeof UnitsIdRoute
  '/accounting/': typeof AccountingIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/maintenance/': typeof MaintenanceIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/units/': typeof UnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/properties/$id'
    | '/units/$id'
    | '/accounting/'
    | '/contracts/'
    | '/documents/'
    | '/maintenance/'
    | '/payments/'
    | '/properties/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
    | '/tenants/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/properties/$id'
    | '/units/$id'
    | '/accounting'
    | '/contracts'
    | '/documents'
    | '/maintenance'
    | '/payments'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/tenants'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/reset-password'
    | '/properties/$id'
    | '/units/$id'
    | '/accounting/'
    | '/contracts/'
    | '/documents/'
    | '/maintenance/'
    | '/payments/'
    | '/properties/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
    | '/tenants/'
    | '/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  UnitsIdRoute: typeof UnitsIdRoute
  AccountingIndexRoute: typeof AccountingIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  MaintenanceIndexRoute: typeof MaintenanceIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
  UnitsIndexRoute: typeof UnitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/': {
      id: '/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof UnitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/': {
      id: '/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof MaintenanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/': {
      id: '/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AccountingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units/$id': {
      id: '/units/$id'
      path: '/units/$id'
      fullPath: '/units/$id'
      preLoaderRoute: typeof UnitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  UnitsIdRoute: UnitsIdRoute,
  AccountingIndexRoute: AccountingIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
  MaintenanceIndexRoute: MaintenanceIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
  UnitsIndexRoute: UnitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
